pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn clean package'
            } //end of steps
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                } //end of success
            } //end of post
        } //end of stage
    } //end of stages
} //end of pipeline
